# Generated by Django 5.0.4 on 2024-07-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
